### ISSUE TITLE
Cannot Login in?

### ISSUE THREAD

**Issue by andy91129** [a1phat0ny/InstaScrape#1]
$ instascrape login

    Choose Account

(1) + Login New Account

choice> 1
Username: XXXXXXXX
Password: 
Traceback (most recent call last):
  File "/usr/local/bin/instascrape", line 11, in <module>
    load_entry_point('instascrape-ax==1.1.0', 'console_scripts', 'instascrape')()
  File "/usr/local/lib/python3.7/site-packages/instascrape_ax-1.1.0-py3.7.egg/instascrape/cli.py", line 637, in main
  File "/usr/local/lib/python3.7/site-packages/instascrape_ax-1.1.0-py3.7.egg/instascrape/cli.py", line 212, in login
  File "/usr/local/lib/python3.7/site-packages/instascrape_ax-1.1.0-py3.7.egg/instascrape/instascraper.py", line 122, in login
KeyError: 'authenticated'

____________________________________________________________________________________________________

Any suggestion?

**Comment by a1phat0ny** [comment]
Hi @andy91129,

Try disabling the two-factor authentication if it is enabled.
InstaScrape does not support 2FA currently. I will try to implement this if I have time.

Thanks for the issue!
