### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Gahamelas** [a1phat0ny/instascrape#13]
When typing the demo:

` instascrape down @emmawatson -timeline -PF "likes_count >= 1000000" -l 100 --preload -d ~/Pictures/Instagram`

I get the error
```
Traceback (most recent call last):
  File "/usr/local/bin/instascrape", line 5, in <module>
    from instascrape.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/instascrape/__init__.py", line 4, in <module>
    from helpers import extract_email
ModuleNotFoundError: No module named 'helpers'
```

**Comment by a1phat0ny** [comment]
You probably installed another different package. This package name should be `instascraper`, not `instascrape`.
