### ISSUE TITLE
python setup.py problem

### ISSUE THREAD

**Issue by kh3rad** [a1phat0ny/instascrape#7]
i canot setup with setup.py and thse are my result
```
[root@s2 InstaScrape]# python3.7 setup.py install
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    version=find_version_number(),
  File "setup.py", line 42, in find_version_number
    raise RuntimeError("version number not found")
RuntimeError: version number not found
```

**Comment by a1phat0ny** [comment]
Oh i'm sorry! This was a mistake. I forgot to move the `__version__` variable to `__init__.py`.
Btw, Instascrape v2.0.0 has just released, please try it out!
Thanks for your contributions!
